### ISSUE TITLE
Count Unique Users

### ISSUE THREAD

**Issue by tinypell3ts** [open-format/subgraph#39]
## Problem
The Graph does not support the count function, and there is a need to track the number of unique users interacting with OPENFORMAT smart contracts, identified by wallet addresses emitted in events.

## Solution
Implement a mapping function within the Subgraph that keeps track of unique wallet addresses as they are emitted by smart contract events.
```[tasklist]
### Tasks
- [x] Define a new entity `Stats` in the schema
- [x] Update the `loadOrCreateUser` function to increase the `uniqueUsers` value in the new `Stats` entity
```

**Comment by tinypell3ts** [comment]
## Stats entity example
```
type Stats @entity {
  uniqueUsers: BigInt!
}
```

## loadOrCreateUser
https://github.com/open-format/subgraph/blob/main/src/helpers/loadOrCreate.ts#L99C12-L116

Increase the `uniqueUsers` when a new user is created.

**Comment by refugene** [comment]
PR https://github.com/open-format/subgraph/pull/42
